### ISSUE TITLE
Huh?

### ISSUE THREAD

**Issue by jimdgit** [OpenDroneMap/UAVArena#3]
![image](https://user-images.githubusercontent.com/7762907/98754656-2acb5500-2395-11eb-802c-fdde3753b8b9.png)

**Comment by jimdgit** [comment]
All I get is this???

**Comment by manand881** [comment]
it should be working now

**Comment by jimdgit** [comment]
So the purpose of this is to compare two cartoons?
Where are the images from the other processors?

**Comment by manand881** [comment]
it should be there, i just checked it

**Comment by jimdgit** [comment]
I deleted it and recloned it it's the same. I assume all I have to do is open index.html in a bowser.
There are no tif images.

**Comment by manand881** [comment]
Do you have python installed ?

**Comment by manand881** [comment]
If yes run the command `python -m http.server 8080` in the project folder and open localhost:8080 in your web browser

**Comment by jimdgit** [comment]
That makes it work. Might want to mention that in the read me.

BTW you need to use python3 for that to work. On mac python runs 2 and python3 runs 3.
python3 -m http.server 8080

**Comment by jimdgit** [comment]
Why don't you just put this on a web site? It would be great for all to see.

**Comment by jimdgit** [comment]
![Uploading image.png…]()

**Comment by jimdgit** [comment]
![Uploading image.png…]()

**Comment by jimdgit** [comment]
So still some issues.

**Comment by manand881** [comment]
where are you uploading images to?

**Comment by jimdgit** [comment]
I pasted them in. That worked the first time.
![image](https://user-images.githubusercontent.com/7762907/98814571-da371480-23f3-11eb-83c6-069f7b7646bd.png)

**Comment by jimdgit** [comment]
You need to let it finish uploading when you paste.
![image](https://user-images.githubusercontent.com/7762907/98814700-0a7eb300-23f4-11eb-99b1-0ed4e067b029.png)

**Comment by manand881** [comment]
i really dont feel like you have to paste anything,

**Comment by jimdgit** [comment]
Only Aukerman seems to work. You need to try more combinations in your testing.
Another odd thing is the on the left selection, if you pick ODM 2.1.1 it pops back to ODM 0.9.9

**Comment by manand881** [comment]
just view it on github pages if thats all you want to do

**Comment by jimdgit** [comment]
The pasting refers to the images in my message here not in your app.
If you paste an image into an issue you need to let it finish uploading.

**Comment by jimdgit** [comment]
> just view it on github pages if thats all you want to do

How do I do that?

**Comment by manand881** [comment]
[click here](https://opendronemap.github.io/UAVArena/)

**Comment by jimdgit** [comment]
No better:
![image](https://user-images.githubusercontent.com/7762907/98815739-99d89600-23f5-11eb-86a7-baa7edf31e7e.png)

**Comment by manand881** [comment]
give it a day, ive generated a pull request for it, its yet to be merged into master

**Comment by jimdgit** [comment]
I just went to you repo and cloned your fork.
Works better, but you still can't select ODM 2.1.1 on the left side.

**Comment by jimdgit** [comment]
Anyway thanks for all your help much appreciated. It's worth while to show that ODM is just as good.

**Comment by pierotofy** [comment]
Looks like this has been resolved :+1: 

@jimdgit if some instructions are missing, please consider contributing to our README to add notes that have been useful to you, which might be useful to others in the future.
